---

- name: cisco
  hosts: switches
  gather_facts: no

  tasks:
  - name: set ftp username and password
    cisco.ios.ios_config:
      lines:
      - ip ftp username ##HERE##
      - ip ftp password ##HERE##

  - name: turn off prompt
    cisco.ios.ios_config:
      lines: file prompt quiet

  - name: backup running-config to ftp
    cisco.ios.ios_command:
      commands: copy running-config ftp://##HERE##/backup/{{ inventory_hostname }}/{{ inventory_hostname }}

  - name: turn on prompt
    cisco.ios.ios_config:
      lines: file prompt alert

  - name: delete ftp username and password
    cisco.ios.ios_config:
      lines:
      - no ip ftp username ##HERE##
      - no ip ftp password ##HERE##
