---

- name: cisco
  hosts: switches
  gather_facts: no

  tasks:
  - name: set ftp username and password
    cisco.ios.ios_config:
      lines:
      - ip ftp username headdns
      - ip ftp password 123456

  - name: turn off prompt
    cisco.ios.ios_config:
      lines: file prompt quiet

  - name: backup running-config to ftp
    cisco.ios.ios_command:
      commands: copy running-config ftp://172.16.119.40/backup/{{ inventory_hostname }}/{{ inventory_hostname }}

  - name: turn on prompt
    cisco.ios.ios_config:
      lines: file prompt alert

  - name: delete ftp username and password
    cisco.ios.ios_config:
      lines:
      - no ip ftp username headdns
      - no ip ftp password 123456
