---

- name: cisco
  hosts: switches
  gather_facts: no

  tasks:
  - name: restore backup to running config
    cisco.ios.ios_command:
      commands: copy ftp://192.168.110.143/restore.conf running-config
